services:
  cmd:
    build: ./cmd
    env_file:
      - ./cmd/.env
    volumes:
      - ./cmd/bin:/opt/bin
      - ./tmp/:/data
    command: rio glui /data/nlcdlc2019cogeo.tif
    ports:
      - 8080:8080
  db:
    image: postgis/postgis:latest
    env_file:
      - ./db/.env
    ports:
      - 5432:5432
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
  web:
    build: ./web
    ports:
      - 80:80
    volumes:
      - ./tmp:/usr/share/nginx/html/cog
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
  tile:
    image: pramsey/pg_tileserv
    ports:
      - 7800:7800
    env_file:
      - ./db/.env
    depends_on:
      - db
  cache:
    image: eeacms/varnish
    ports:
      - "8888:6081"
    environment:
      BACKENDS: "raster_tile_1:7800"
      PARAM_VALUE: "-p default_ttl=6000"
      VARNISH_SIZE: "2G"
    depends_on:
      - tile
  mbtileserver:
    image: consbio/mbtileserver
    ports:
      - 8000:8000
    volumes:
      - ./tmp/mbtiles:/tilesets
volumes:
  pgdata:
